### ISSUE TITLE
Undertale Project Schema and New Tasks

### ISSUE THREAD

**Issue by ebeshero** [ajw120/Undertale#10]
* @Bennediction and @bobbyfunks met with @ebeshero , @KSD32 , and @alnopa9 today and finished revising the waterfall.xml file, and made some decisions about reorganizing the files. 
* Each setting gets its own XML file, and *inside* are `<path>` elements that contain the various routes of game place. @Bennediction will reorganize and explain. 
* @ajw120 will need a briefing on all this--hopefully after class on Friday
* **[A new schema](https://github.com/ajw120/Undertale/tree/master/schema)** is complete and ready to go, but will need some refinements on attribute values (see comments in the schema). 
* You'll also want a little Schematron. @Bennediction is on this. 
* Undertale Team is meeting again next Thursday 11/14 at noon, hopefully with all markup revised according to new schema. (We're giving Undertale Team an extension on evaluating Checkpoint 4 until 11/14 accordingly, b/c Checkpoint 4 is about finishing the markup.)

**Comment by ebeshero** [comment]
Actually, looking ahead at next week, I would say Undertale has now completed Checkpoint 4 with the major decisions made yesterday and the schema revision. Checkpoint 5 is due next week anyway, and asks for completion of revised markup as well as progress on the website.

**Comment by bobbyfunks** [comment]
are we still meeting today?
