### ISSUE TITLE
Git Bash Not Working Again

### ISSUE THREAD

**Issue by ajw120** [ajw120/Undertale#14]
Hey guys, 

My git bash is being stupid again and wont let me push and pull any thing from the undertale folder from github. It is also doing this for my GitHub folder too. I don't know what's keeping it from pushing or pulling, I will try to figure it out. But I just wanted to inform you guys and apologize for no new content being added on here.

**Comment by ebeshero** [comment]
@ajw120 I just now did a `git pull` on Undertale and I can see there are updates from the past week in the HTML and the XML directories (I see @bobbyfunks just pushed a pretty major update of Ruins.xml and some new HTML and CSS).  If your updates are in these directories or to Ruins.xml you might have a merge conflict...I can try and walk you through it if you want to try to solve it.

**Comment by ebeshero** [comment]
@ajw120 One thing you may want to do is `git add` first, and then `git pull`. I'm thinking you might have edited a file that one of the others was working on, so GitHub is being (sigh) extra careful to prevent overwriting your work.
