### ISSUE TITLE
A Necessity For This Project

### ISSUE THREAD

**Issue by ajw120** [ajw120/Undertale#19]
Dr. B!

We really want to include an aspect from the original Undertale website onto our site!

It's a dog on the bottom of his page and when you mouse over it, it sticks its tongue out and barks. The dog is a character from the game. 
I'm stuck on how to include this feature. 

[https://undertale.com/](url)

Here is the link to the website. The dog is at the very bottom.
@ebeshero

**Comment by ebeshero** [comment]
@ajw120 @bobbyfunks @Bennediction Okay, so I'm looking at that barking dog image, or really, two images. And their javascript (or rather, awful JQuery) is absolutely impenetrable and rotten, so I think if you're going to do this, you can do it better than they did. The two images are presumably freely available to work with, and you can find them here: https://undertale.com/assets/images/

You need those two images on the server, first of all, and on click of one, it's to be replaced by the other. This is something like an "animated gif", so I'm going to look up and see how we can do it...

**Comment by ebeshero** [comment]
The images are: 
dog.png : https://undertale.com/assets/images/dog.png
dog-bark.png :   https://undertale.com/assets/images/dog-bark.png

**Comment by ebeshero** [comment]
Make sure you credit and link out to the sources for all your images somewhere on your site!  (That could go in a footer area, for example, where you also provide your Creative Commons license.)

**Comment by ajw120** [comment]
Will do! Thank you!

**Comment by ajw120** [comment]
I am currently stuck trying to get this to work. 

I have 
```
.barking-dog {
    width: 400px;
    height: 142px;
    margin-left: 353px;
    margin-top: -70px;
    padding-bottom: 16px;
}

.barking-dog:hover {
    background: url(dog-bark.png);
    background-repeat: no-repeat;
}
```
in `<style>`

and `<div id="barking-dog">
            <a href="#" id="dog"><img src="images/dog.png" alt="Annoying Dog" /></a>
        </div>` 

in the `<body>` 

I have read tutorials and nothing seems to be working for me.

**Comment by ebeshero** [comment]
@ajw120 At first glance, I see there is definitely a mismatch between your CSS and the HTML here. This notation: `.barking-dog` designates a `@class` attribute, but your HTML has an `@id` attribute. For that you need `#barking-dog`. I'm not sure if that resolves anything, as I have not otherwise tested your code, but try fixing that and let's see what happens...

**Comment by ajw120** [comment]
It did not :(

**Comment by ebeshero** [comment]
@ajw120 Yeah, I'm trying it now and I see it's not working... I think there are other problems in the HTML code. This link doesn't make sense to me: `<a href="#" id="dog">...</a>` because it doesn't go anywhere.

Can you post a link to the tutorial you're working with?

**Comment by ajw120** [comment]
I was working with this one first:
https://www.tutorialrepublic.com/faq/how-to-change-image-on-hover-with-css.php

**Comment by ebeshero** [comment]
@ajw120 I think doing this with JavaScript makes a lot more sense. I'm looking at https://stackoverflow.com/questions/6764961/change-an-image-with-onclick/41542141

**Comment by ebeshero** [comment]
@ajw120 Actually, though, that tutorial link you posted looks pretty good. Let me take a closer look at both...

**Comment by ebeshero** [comment]
@ajw120 I got it working! Your tutorial was good and helpful--we just needed to make sure we were applying it properly. So here's what I have:
In `<style>` where you had it: 

```
 #barking-dog {
            background: url(images/dog.png);
            background-repeat: no-repeat;
            
   width: 400px;
    height: 142px;
    margin-left: 353px;
    margin-top: -70px;
    padding-bottom: 16px;
}

#barking-dog:hover {
    background: url(images/dog-bark.png);
    background-repeat: no-repeat;
}
```
And in the `<body>` element, just an *empty* `<div id="barking-dog">`. (Don't put an image tag inside that.)
```
<div id="barking-dog"></div>

```

**Comment by ebeshero** [comment]
@ajw120 oops: I see I was trying to comment out your other CSS properties, but they're fine, as long as they're working for you:

```
 #barking-dog {
            background: url(images/dog.png);
            background-repeat: no-repeat;
            
   width: 400px;
    height: 142px;
    margin-left: 353px;
    margin-top: -70px;
    padding-bottom: 16px;
}

#barking-dog:hover {
    background: url(images/dog-bark.png);
    background-repeat: no-repeat;
}

```

**Comment by ebeshero** [comment]
And the HTML is really just:

```
<div id="barking-dog"></div>
```

**Comment by ajw120** [comment]
It worked!!!

**Comment by ebeshero** [comment]
@ajw120 okay--are you posting stuff on the web server? Or is that one of the other team members? I made the clickable image map on the index.html page be responsive to resizing the window, and there's a script file to add to the server... 

Here's what needs to go up:
* `index.html`
* a JQuery script that you're only allowed to use b/c I'm the one applying it: `jquery.rwdImageMaps.min.js`
* updated copy of `images/map_undertale.jpg`

 (Sidenote: I don't usually permit students to post JQuery library stuff because it comes from unknown sources and might cause problems on my server, but this one seems like a good idea and I might allow it *just* for image map applications).

**Comment by ajw120** [comment]
That's all on Robby's computer.

**Comment by ebeshero** [comment]
@bobbyfunks Hey there! Can you post these new/modified files on the newtfire Undertale site?

Here's what needs to go up:
* `index.html`
* a JQuery script that you're only allowed to use b/c I'm the one applying it: `jquery.rwdImageMaps.min.js`
* updated copy of `images/map_undertale.jpg`
* `images/dog.png`
* `images/dog-bark.png`

**Comment by ebeshero** [comment]
@bobbyfunks (Do a `git pull` first.) In fact, *everyone* do a `git pull`.
@Bennediction @ajw120
