### ISSUE TITLE
A Possible Take on This Project

### ISSUE THREAD

**Issue by ajw120** [ajw120/Undertale#2]
There are, that I know, three possible ways to play this game. 

There is Neutral, Pacifist, and Genocide. 

I was thinking, since there are three of us, that each of us could go through the scripts for each of of these (you guys can pick what you'd like to do) and then we can start putting these scripts and scenes into XML and actually get some markups going. 

We can discuss this fully after class today if you'd like, regarding what we are marking up. 

There is just a lot of content and I think it would be wise to get a start on that as soon as possible! If we can anyway. 

Below I will have a link to the entire script that I found. It is broken down into sections and into scenes, then into which path you would decide to take!
[https://drive.google.com/drive/folders/0B6gS2LPXdIc5Zll6YzVna3dZQms](url)

**Comment by cozyycoding** [comment]
I like this idea, but there's some degree of overlap between the three routes, especially between neutral and pacifist e. g. the sequence where you first meet Sans and Papyrus. Going in this manner might result in us doing the same exact scene twice. I propose that we instead divide the work by different locations, like how it's divided in the google drive to avoid redundancy.

**Comment by ajw120** [comment]
Definitely a good call. That sounds perfect to me.
