### ISSUE TITLE
Markdown file

### ISSUE THREAD

**Issue by cozyycoding** [ajw120/Undertale#21]
There's some confusion on our team as to what all goes into the markdown file, could you clarify what all needs to be in it? @ebeshero

**Comment by ebeshero** [comment]
@Bennediction Are you referring to the main Readme.md that appears on this GitHub repo? You could include a link out to your project website from there. But markdown files in your repo are really supposed to help with the process of your project to communicate with the team. 

On your website somewhere you will want an explanation of your project and something discussing your methods of markup. You could make links to specific files in your repo to help document things like your schema and how you analyzed your markup. Hope that helps!

**Comment by cozyycoding** [comment]
yes it does, thank you
